#title: Minimal theme
#logo: /assets/img/logo.png
#description: Minimal is a theme for GitHub Pages.
#how_downloads: true
#google_analytics:
#theme: jekyll-theme-minimal

titel: Diego Diaz
#logo: /assets/img/##picturefile##
description: Data Scientist 
show downloads: true 
theme: jekyll-theme-minimal 
